### ISSUE TITLE
前端API確認 - Account

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#1]
Account我跟Wesley原本預計是我們發給隊輔一個team code，系統驗證成功之後會回給我們一個bearer token
個人覺得再加一個username（隊伍名稱）好像沒有特別必要？

然後logout這個endpoint有什麼特別的效用嗎？（看起來目前的login回傳的也是username跟password，好像不是token，所以logout也沒有必要invalidate token？）

最後隊伍名字的方面預計是一隊一個帳號 然後就直接一個隊伍名 不會有姓、名/Email，也不會讓user自己register（我們會幫他在活動前就做好）

不過其實把每個人都開一個帳號出來也是一個可行的做法，只是我個人不覺得有必要弄的這麼麻煩就是了。我有什麼漏想的地方嗎？

**Comment by fan9704** [comment]
Account 這類型 API 可以忽略不要看，隊伍驗證的地方都在 Team API 這邊
例如你要的 Token 驗證在 team/token 這條 API 下，跟我們的共識是一樣的
只是我做的一個 Account API 作為保留如果有需要後續再來弄他

**Comment by fan9704** [comment]
目前 Team 的創建方法
Post /api/team
給予 小隊名稱 與 四位英數混合(四碼非常夠用)的 token
後續就可以用 token + 小隊名稱進行驗證

**Comment by fan9704** [comment]
修改內容
[PR #3 ](https://github.com/fan9704/Drawing-Competition-Backend/pull/3)
