### ISSUE TITLE
[Feat]: 統計相關 API 是否需要修改

### ISSUE THREAD

**Issue by fan9704** [fan9704/Drawing-Competition-Backend#10]
### Contact Details

cxz123499@gmail.com

### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

是否需要在 Statistic API 進行新增功能與修改

### 提供相關的技術或實作參考 Relevant technical or implementation references

已經使用 Vue3 進行過測試
Teckstack
- Apache EChart

[範例專案](https://github.com/fan9704/Drawing-Competition-Frontend/blob/master/src/views/statistic/IndexView.vue) 

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
CC: @burnedinthesky

**Comment by burnedinthesky** [comment]
目前前端還在慢慢整合中，在整合的時候如果有碰到問題會再丟過來

**Comment by fan9704** [comment]
![image](https://github.com/fan9704/Drawing-Competition-Backend/assets/76801598/542d5a93-8288-4c56-af97-1847f4f72bce)

以上是我的實作成效
