### ISSUE TITLE
[Bug]: Submissions中stderr為必填

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#12]
### 發生了甚麼? What happened?

Submissions中stderr為必填（如果沒有stderr是預計直接放空白字串嗎？還是應該是null呢？）

### OS Version

MacOS

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
Submissions中stderr為必填（如果沒有stderr是預計直接放空白字串嗎？還是應該是null呢？）
> 空白字串 可以詳見 api > model > submission
