### ISSUE TITLE
[Feat]: 把Challenge的Description拆成Title + Description

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#13]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

在我的預想中每個題目的Title跟Description會是分開的兩個欄位
像是Leetcode或是ZeroJudge那樣（[範例](https://zerojudge.tw/ShowProblem?problemid=a001)）
然後讓我們在description裡面寫點注意事項/幹話
看FKT跟Wesley的想法？
cc @fan9704 @aa35037123 

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
我其實一開始覺得是連 description 都不用啦(反正學員看到圖就直接畫了)
不過我覺得欄位多 是都沒差

**Comment by burnedinthesky** [comment]
> 我其實一開始覺得是連 description 都不用啦(反正學員看到圖就直接畫了)

是這樣沒錯 不過我自己是覺得有點幹話比較人性化就是了

**Comment by aa35037123** [comment]
我覺得題目名稱的確需要，但不急著做，目前目標先把整個流程串在一起

**Comment by fan9704** [comment]
同意 基本功能先有 我們再求其美
這件事優先級先不要這麼高就好

**Comment by burnedinthesky** [comment]
主要會開是因為前端期待有title + description
所以目前沒有的話前端沒辦法整合

**Comment by fan9704** [comment]
還好吧 沒有 title 先 title 跟 description 顯示在 frontend 的地方都先用 description 顯示就好


到時候 title 欄位出來了再改不會太麻煩

**Comment by burnedinthesky** [comment]
Ok 那我先用desc頂著
