### ISSUE TITLE
[Feat]: API Endpoint for "{round_id}所有隊伍的分數"

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#14]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

既有的/statistic/round/allTeam 但是限定一個round_id（e.g., /statistic/round/{round_id}/allTeam）
之前我跟 @aa35037123 在討論的時候是預計在遊戲結束時才公布總計分板 在那之前每個隊伍都只看得到當前round的計分版
這樣做是怕最一開始落後的隊伍 發現Round 2/Round 3落後的太多就乾脆放棄了
也可以加上一點刺激感 不到最後不知道誰贏誰輸

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
就單 Round 的版本對吧
那我會再開新的 API 這個先保留

**Comment by fan9704** [comment]
對了那我們 Round 之間的間隔
這段時間我以為是來看所有隊伍的表現與排名欸

**Comment by burnedinthesky** [comment]
沒誒 目前我是預計直接寫一個「現在沒有round」

**Comment by fan9704** [comment]
欸都我是問說 Round1 Round2 應該中間會休息？ 總之就是有段時間 有需要公告當前各組的表現嗎

就不用說整個遊戲結束再公布,可以讓各組知道排名的提升 下降的過程還蠻有趣的

**Comment by burnedinthesky** [comment]
有 我懂 不過我覺得好像等到最後再公布比較刺激？
今晚會議來討論一下好了

**Comment by fan9704** [comment]
那這個 Issue 應該可以關閉了

**Comment by fan9704** [comment]
> 就單 Round 的版本對吧
那我會再開新的 API 這個先保留

靠杯根本還沒做 扯遠了

**Comment by burnedinthesky** [comment]
抱歉我沒有注意到，但我在這個API的Endpoint除了total以外還需要一個每題分數多少的list（其時有這個也不一定需要total啦）
list我原本預期是一段整數 不過這樣想想怎麼排序這些整數好像會是個需要思考的點？（直接照Challenge ID的大小嗎？）
前端呈現起來會像這樣
![image](https://github.com/fan9704/Drawing-Competition-Backend/assets/40905726/86e13994-294c-4b42-a903-1040295a4916)

**Comment by fan9704** [comment]
> 抱歉我沒有注意到，但我在這個API的Endpoint除了total以外還需要一個每題分數多少的list（其時有這個也不一定需要total啦）
list我原本預期是一段整數 不過這樣想想怎麼排序這些整數好像會是個需要思考的點？（直接照Challenge ID的大小嗎？）
前端呈現起來會像這樣

那就先以 List 為主好了 ID 小到大排序

**Comment by fan9704** [comment]
PR #21  已經完成功能
