### ISSUE TITLE
[Bug]: /challenges/{challenge_id} 在碰到不存在的challenge id時會丟500

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#15]
### 發生了甚麼? What happened?

後端應該catch之後丟404比較合理？

### OS Version

MacOS

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
500反而不合理吧  Internal Server Error
404 就是正常的沒有 Retrieve 到

**Comment by fan9704** [comment]
有出現 500 的話 應該可能純 typo 再去修

**Comment by fan9704** [comment]
Ok 我知道為什麼了 這條 API 沒有 
Retreivie 不到的 null safety 
到時候我會用 generic view 來改

**Comment by burnedinthesky** [comment]
> 500反而不合理吧 Internal Server Error
嘿對 這就是為什麼我開這個issue

**Comment by fan9704** [comment]
Done Please Refer
https://github.com/fan9704/Drawing-Competition-Backend/pull/16
