### ISSUE TITLE
前端API確認 - Round & Challenge

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#2]
Round跟Challenge的Post好像該用Admin Only保護起來？

然後一個submission應該還會需要紀錄吻合度（不是分數）、stdout跟stderr，所以可能得小調一下model

然後round還需要一個leaderboard的endpoint，回傳目前這個round每一隊各題的分數
<img width="929" alt="image" src="https://github.com/fan9704/Drawing-Competition-Backend/assets/40905726/dda7ea4c-3f88-407c-ae9e-38a938b6edf9">

前端這邊還需要一個challenge前三高分的隊伍的各隊最高分submission資料的endpoint

<img width="803" alt="image" src="https://github.com/fan9704/Drawing-Competition-Backend/assets/40905726/2314cc72-b9cf-4bfd-84a1-ef67f501b1b9">

**Comment by fan9704** [comment]
1. Re: Round跟Challenge的Post好像該用Admin Only保護起來？
    - 會希望不開 API 的意思嗎，要建立 Round/Challenge 全部到後台去用就好了對吧 如果 OK 其實就把他從 Router 拔掉就好
2. Re:Submission Model 確認一下是要
    - 刪掉 score 欄位，
    - 新增 吻合度(不知道要叫做甚麼 matching?)
    - 新增 stdout 輸出
    - 新增 stderr 例外輸出
3. 這方面的後端修改 Model 沒什麼問題，主要回傳的內容需要由 Judge 系統來給予實際協助
  
CC: (Weslly) @aa35037123

**Comment by aa35037123** [comment]
應該不是刪掉分數，分數和 Submission 是絕對相關的，目前是要討論 Submission 中有需要多紀錄 fitness、程式總行數、執行時間嗎

CC: @burnedinthesky @fan9704

**Comment by fan9704** [comment]
恩恩同意 @aa35037123 
我覺得如果以新增欄位替代修改會比較好，此外新增欄位也比較不會去影響舊有欄位的相關功能

那最後敲定  Submission Model 為這樣
保留 Score
新增 
- fitness 吻合度
- line_number 程式行數
- execute_time 執行時間

這部分數據的處理也需要在 Judge System @aa35037123  那邊提供對於程式檢驗的數據，當然如果像是 line_number 這類在檔案上傳時前端能檢驗的話是最好  @burnedinthesky 

![image](https://github.com/fan9704/Drawing-Competition-Backend/assets/76801598/9fa998e5-a05c-45a2-b180-14e16dc6de49)

有任何建議歡迎提供

CC: @aa35037123  @burnedinthesky

**Comment by burnedinthesky** [comment]
> 會希望不開 API 的意思嗎，要建立 Round/Challenge 全部到後台去用就好了對吧 如果 OK 其實就把他從 Router 拔掉就好
這倒也不一定，主要是看後端目前打算怎麼處理Auth
我自己目前是想有兩種做法

第一種是我們把部分Django Admin的東西也開一個API Endpoint
那這樣API的Auth就應該分三種：No Limit（eg：登入的Endpoint）、Authenticated Only（給團隊用的，例如Submit一支程式）、Admin Only（只給我們用的，例如開一個新隊伍或是改動Round的資料）

第二種就是我們全部都用Django Admin來管理資料，那這樣就不用再處理Admin Only的API

我自己是偏好第二種，畢竟這樣比較簡單，我也一時之間想不出來Admin的東西再開一個API出來有什麼好處
不過我記得 @fan9704 是支持再開一個API出來的？FKT的看法呢？

**Comment by burnedinthesky** [comment]
> 當然如果像是 line_number 這類在檔案上傳時前端能檢驗的話是最好
我自己是偏好所有的metric全部都是後端計算，畢竟前端的code是可以被使用者篡改的（雖然不知道學員有沒有這個能力就是了），不過我覺得既然前後端implement的難度都差不多簡單（Python應該直接`code.count("\n")`就好），那後端寫放心一點 
cc @aa35037123

**Comment by fan9704** [comment]
Re: 
> 我自己是偏好所有的metric全部都是後端計算，畢竟前端的code是可以被使用者篡改的（雖然不知道學員有沒有這個能力就是了），不過我覺得既然前後端implement的難度都差不多簡單（Python應該直接code.count("\n")就好），那後端寫放心一點
cc @aa35037123

同意

這部分要請 @aa35037123 協助了

**Comment by fan9704** [comment]
Re:
> 這倒也不一定，主要是看後端目前打算怎麼處理Auth
我自己目前是想有兩種做法

第一種是我們把部分Django Admin的東西也開一個API Endpoint
那這樣API的Auth就應該分三種：No Limit（eg：登入的Endpoint）、Authenticated Only（給團隊用的，例如Submit一支程式）、Admin Only（只給我們用的，例如開一個新隊伍或是改動Round的資料）

第二種就是我們全部都用Django Admin來管理資料，那這樣就不用再處理Admin Only的API

我自己是偏好第二種，畢竟這樣比較簡單，我也一時之間想不出來Admin的東西再開一個API出來有什麼好處
不過我記得 @fan9704 是支持再開一個API出來的？FKT的看法呢？


我個人偏好第二種，但目前是把不需要的 API 都關掉了，新開 API原本的用意是可能會有 Frontend 給工作人員方便新增 Challenge/Round 等內容的介面，但確實用 Admin 比較方便

**Comment by burnedinthesky** [comment]
看起來我跟FKT都有共識 我自己也覺得直接用Admin就好
那就再請FKT在router上把admin相關的route拔掉了～感謝

**Comment by aa35037123** [comment]
由於用 line_number 來 Judge 會有作弊的嫌疑（把所有 code 縮成同一 Line），所以想把這個 attribute 改成 word_count 


cc: @fan9704

**Comment by fan9704** [comment]
可以

**Comment by burnedinthesky** [comment]
不過我們有好用的word_count計算器嗎？
例如 `draw_fn = lambda fn_list: [x() for x in fn_list` 要怎麼算幾個word？

**Comment by burnedinthesky** [comment]
然後 @aa35037123 要不要再開一個新的issue出來啊 
感覺這個在一個新issue討論比較合理

**Comment by fan9704** [comment]
這偏向另一個議題 可以再開 Issue
