### ISSUE TITLE
[Feat]: 把Challenge加上"難度"欄位

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#23]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

之前跟 @aa35037123 討論過的功能
每個Challenge應該會有個enum叫做difficulty 標示easy | medium | hard
讓菜雞比較好判斷哪題是自己該寫的

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
完成
