### ISSUE TITLE
[Bug]: /round不該回傳list

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#24]
### 發生了甚麼? What happened?

在設計上遊戲應該最多只會有一個round在進行（不會有兩個round同時進行的狀況）
所以/round（詳見 #7 ）應該不會回傳陣列才對（應該會是RoundData | null）之類的

### OS Version

MacOS

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
聽起來你忽略這個 API 就沒問題了

**Comment by fan9704** [comment]
完成
