### ISSUE TITLE
[Feat]: 開放索取一個Challenge前三高分的隊伍的Submission細節的API

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#27]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

在顯示一個特定 challenge 的 leaderboard 使用
<img width="791" alt="image" src="https://github.com/fan9704/Drawing-Competition-Backend/assets/40905726/49a474ab-64c8-4e09-8e72-7f8f6d56c2bc">

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
沒問題 我應該會開在 statistic api

**Comment by fan9704** [comment]
![image](https://github.com/fan9704/Drawing-Competition-Backend/assets/76801598/781fb30e-6f22-4165-8dae-fa3450eb9914)

是想要這樣的結果嗎，我這邊試作了一版了

**Comment by burnedinthesky** [comment]
前端整合成功！PR Merge 進 master 就可以關 issue 了
