### ISSUE TITLE
[Disc] 討論：Round的檢視機制

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#28]
Round 目前是否能被使用者看到是基於 is_valid 這個 flag ，但直觀上好像應該是由系統自動判定的
就是在 start_time 到 end_time 這個區間內可見，其他時候都不可見
這樣可以省去每次 round 結束時都要課活組有人手動去取消勾選的麻煩

**Comment by fan9704** [comment]
這個做法好像不錯 
其實也就改一條 api 而已對吧
api/round/
在邏輯這邊去偵測時間就可以了

**Comment by fan9704** [comment]
@burnedinthesky @aa35037123 
兩位覺得如何

**Comment by burnedinthesky** [comment]
對啊 其實要改的應該不多
我自己蠻支持以時間做判斷的作法的

**Comment by burnedinthesky** [comment]
看起來三個人都有共識 應該可以直接 merge #31 了
