### ISSUE TITLE
[Feat]: 在遊戲結束時重新導向玩家到前端 /results

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#29]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

在遊戲結束時，讓 /round API 回傳一個 redirect ，導向到前端的 /results 頁面

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
Redirct 應該是前端去實踐
如果需要實作這個功能 我想應該是後端在沒有符合時間內的 round 的時候 可能回傳個 204 然後前端根據這個 status 去 redirect 到特定的 components?

**Comment by burnedinthesky** [comment]
後端是可以做 Redirect 的請求的
FastAPI的版本就是RedirectResponse
不由前端實作的原因是因爲怕API太混頓

因為由前端做的方法有兩種
1. 改/round api
但這樣response shape又多加了一個 而且game concluded在round回覆感覺怪怪的
2. 開一個新的endpoint
但這樣前端要同時等兩個api的回應
怕增加使用者延遲

所以才想說前端維持在/team這個頁面只call /round這個端點的實作方式
然後由後端這邊回傳遊戲結束 重新導向到看遊戲結果這個方式

**Comment by fan9704** [comment]
Redirect 實務來說不會是由 Backend 去實踐，正確的實作方法真的會是由前端控制。

因此還是建議您採用收到 StatusCode Redirect 的方法 可以參考一下

---

如果您還是想要 Redirect 麻煩提供一下 URL

**Comment by burnedinthesky** [comment]
了解，那我們用204來溝通好了
當前端收到204的時候會再Redirect到看遊戲總結的頁面
