### ISSUE TITLE
[Feat]: 在 /submissions POST的資料欄位中移除 round

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#36]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

目前在提交新的submission的時候需要提供code、team、round、challenge
但因為challenge的id其實在整個DB中是unique的（i.e., round 1 跟 round 2 不會各有一個 challenge 1)
所以round並非必要，且若拔掉於前端實作時更簡易

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
已完成

特別要在回傳型態的地方注意一下
