### ISSUE TITLE
[Feat]: 把 /challenge 與 /rounds 整合成同一個API

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#7]
### 你想要提出什麼樣的新需求/功能? What demand/feature do you want?

目前前端的邏輯是在顯示round頁面時，如果現在有個round正在進行，那就顯示這個round的id與所有的challenge，如果沒有round的話就顯示沒有round。但現在如果前端要判斷有沒有round的方法好像只能透過/challenge/回傳的陣列是不是空的。可否把round/這個endpoint改寫成「如果有round，回傳現在的round的id, start_time, end_time, 所有這個round的challenge；如果沒round，回傳null」，這樣邏輯上好像直觀一點。

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by burnedinthesky** [comment]
其實這樣也代表就不用再額外加一個is_valid，讓challenge&round相關的資料能被存取的時間綁round的開放時間就好（i.e., 在每個request進來的時候檢查是不是現在這個round的開放時間，如果不是就擋掉）

**Comment by fan9704** [comment]
所以簡單來說你需要一個
GET: /challenge/{round_id}/ 的意思嗎 
@burnedinthesky

**Comment by burnedinthesky** [comment]
不太像 主要是希望/round/能夠直接回傳現在正在進行的round
畢竟前端在抓現在round的challenge時不會知道round_id是什麼 
如果還要先call /round得到round_id，再call /challenges/round_id 得到challenges有點多餘
所以會希望/round有這個behavior
有round時回傳round的id start&end_time challenge list
沒round時回傳null

**Comment by fan9704** [comment]
好 我 Try 看看

**Comment by fan9704** [comment]
@burnedinthesky  已經 Merge 進去

**Comment by burnedinthesky** [comment]
看Swagger 感覺沒什麼問題
把 #13 解決掉之後就可以close了

**Comment by burnedinthesky** [comment]
##13

**Comment by burnedinthesky** [comment]
#13
